//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por EntornVGI.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_R                  101
#define ID_INDICATOR_ALFA               102
#define ID_INDICATOR_BETA               103
#define ID_INDICATOR_PVX                104
#define ID_INDICATOR_PVY                105
#define ID_INDICATOR_PVZ                106
#define ID_INDICATOR_COLOR              107
#define ID_INDICATOR_TR                 108
#define ID_INDICATOR_PTR                109
#define ID_INDICATOR_PAS                110
#define ID_INDICATOR_FPS                111
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_EntornVGITYPE               130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_MENU_WINDOW                 310
#define ID_CAMERA_ESFERICA              32771
#define ID_CAMERA_MOBIL                 32772
#define ID_CAMERA_ZOOM                  32773
#define ID_CAMERA_ZOOM_ORTO             32774
#define ID_CAMERA_SATELIT               32775
#define ID_VISTA_POLARS_X               32776
#define ID_VISTA_POLARS_Y               32777
#define ID_VISTA_POLARS_Z               32778
#define ID_CAMERA_POLARS_X              32779
#define ID_CAMERA_POLARS_Y              32780
#define ID_CAMERA_POLARS_Z              32781
#define ID_C32782                       32782
#define ID_CAMERA_NAVEGA                32783
#define ID_CAMERA_ORIGEN_NAVEGA         32784
#define ID_CAMERA_GEODE                 32785
#define ID_CAMERA_ORIGEN_GEODE          32786
#define ID_ARXIU_FRACTAL                32787
#define ID_ARXIU_FITXER                 32788
#define ID_ARXIU_FITXER_FONT_LLUM       32789
#define ID_ARXIU_FITXER_SKYBOX          32790
#define ID_ARXIU_OBRIR_FRACTAL          32791
#define ID_ARXIU_OBRIR_FONT_LLUM        32792
#define ID_ARXIU_OBRIR_SKYBOX           32793
#define ID_ARXIU_OBRIR_OBJ              32794
#define ID_VISTA_FULLSCREEN             32795
#define ID_VISTA_PAN                    32796
#define ID_VISTA_ORIGEN_PAN             32797
#define ID_VISTA_EIXOS                  32798
#define ID_VISTA_SKYBOX                 32799
#define ID_PROJECCI32800                32800
#define ID_PROJECCIO_PERSPECTIVA        32801
#define ID_OBJECTE_CAP                  32802
#define ID_OBJECTE_CUB                  32803
#define ID_OBJECTE_CUB_RGB              32804
#define ID_OBJECTE_ESFERA               32805
#define ID_OBJECTE_TETERA               32806
#define ID_OBJECTE_ARC                  32807
#define ID_OBJECTE_CORBES               32808
#define ID_OBJECTE_CORBES_BEZIER        32809
#define ID_CORBES_LEMNISCATA            32810
#define ID_OBJECTE_CORBES_LEMNISCATA    32811
#define ID_OBJECTE_CORBES_BSPLINE       32812
#define ID_OBJECTE_CORBES_HERMITTE      32813
#define ID_OBJECTE_CORBES_CATMULL_ROM   32814
#define ID_CORBES_PUNTS_CONTROL         32815
#define ID_CORBES_BEZIER                32816
#define ID_CORBES_BSPLINE               32817
#define ID_CORBES_HERMITTE              32818
#define ID_CORBES_CATMULL_ROM           32819
#define ID_CORBES_TRIEDRE_FRENET        32820
#define ID_OBJECTE_TIE                  32821
#define ID_MATRIU_PRIMITIVES            32822
#define ID_OBJECTE_MATRIU_PRIMITIVES_VAO 32823
#define ID_OBJECTE_MATRIU_PRIMITIVES    32824
#define ID_TRANSFORMA_TRASLACIO         32825
#define ID_TRANSFORMA_ORIGEN_TRASLACIO  32826
#define ID_TRANSFORMA_ROTACIO           32827
#define ID_TRANSFORMA_ORIGENROTACI32828 32828
#define ID_TRANSFORMA_ORIGEN_ROTACIO    32829
#define ID_TRANSFORMA_ESCALAT           32830
#define ID_TRANSFORMA_ORIGEN_ESCALAT    32831
#define ID_TRANSFORMA_M32832            32832
#define ID_TRANSFORMA_MOBIL_X           32833
#define ID_TRANSFORMA_M32834            32834
#define D_TRANSFORMA_MOBIL_Y            32835
#define ID_TRANSFORMA_MOBIL_Z           32836
#define ID_TRANSFORMA_MOBIL_Y           32837
#define ID_OCULTACIONS_FRONT_FACES      32838
#define ID_OCULTACIONS_TEST_VISIBILITAT 32839
#define ID_OCULTACIONS_ZBUFFER          32840
#define ID_ILUMINACIO_LLUM_FIXE         32841
#define ID_ILUMINACIO_CARES_FRONT_BACK  32842
#define ID_ILUMINACIO_PUNTS             32843
#define ID_ILUMINACIO_FILFERROS         32844
#define ID_ILUMINACIO_PLANA             32845
#define ID_ILUMINACIO_SUAU              32846
#define ID_IL_REFLECTIVITATMATERIAL     32847
#define ID_REFLECTIVITATMATERIAL_MATERIAL 32848
#define ID_REFLECTIVITATMATERIAL_EMISSI32849 32849
#define ID_MATERIAL_MATERIAL_COLOR      32850
#define ID_MATERIAL_EMISSIO             32851
#define ID_REFLECTIVITATMATERIAL_AMBIENT 32852
#define ID_MATERIAL_AMBIENT             32853
#define ID_MATERIAL_DIFUSA              32854
#define ID_MATERIAL_ESPECULAR           32855
#define ID_IL_TEXTURES                  32856
#define ID_IL_TEXTURA                   32857
#define ID_ILUMINACIO_TEXTURES          32858
#define ID_TEXTURA_IMATGE_SOIL          32859
#define ID_TEXTURA_FLAG_INVERT_Y        32860
#define ID_LLUMS_LLUM_AMBIENT           32861
#define ID_LLUMS_LLUM_0                 32862
#define ID_LLUMS_LLUM_1                 32863
#define ID_LLUMS_LLUM2                  32864
#define ID_LLUMS_LLUM3                  32865
#define ID_LLUMS_LLUM4                  32866
#define ID_LLUMS_LLUM                   32867
#define ID_LLUMS_LLUM5                  32868
#define ID_LLUMS_LLUM32869              32869
#define ID_LLUMS_LLUM6                  32870
#define ID_LLUMS_LLUM32871              32871
#define ID_LLUMS_LLUM7                  32872
#define ID_SHADERS_FLAT                 32873
#define ID_SHADERS_GOURAUD              32874
#define ID_SHADERS_PHONG                32875
#define ID_SHADER_LOAD_FILES            32876
#define ID_SHADER_PBINARY_READ          32877
#define ID_SHADERS_GRAVARBINARYPROGRAM  32878
#define ID_SHADER_PBINARY_WRITE         32879
#define ID_SHADERS_LOAD_FILES           32880
#define ID_SHADERS_PBINARY_READ         32881
#define ID_SHADERS_PBINARY_WRITE        32882

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         32883
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
